### ISSUE TITLE
question

### ISSUE THREAD

**Issue by choccy** [infinityb/rust-irc-bot#3]
how does using mio help this project? i thought it was mostly used for working with many sockets and files.

**Comment by infinityb** [comment]
Hi faiizow,

I get some benefits from mio:
- I don't need separate reader and writer threads (read will block)
  - I don't believe `select()` was available to avoid the threads when I switched to mio.
- Ability to wake up my thread using a channel while it is waiting on I/O
  - Mio uses a pipe internally to do this, which plays well into the event loop model

And here is my major con:
- I'd like to make SSL'd connections to an ircd, but using OpenSSL from within mio is difficult.

After taking into account those things, I found that my code would be better off with mio than without. I didn't particularly want to write a bunch of stuff to get channels and socket I/O to play together nicely and mio already had it figured out.

Also, mio doesn't operate very well with files at this time, there are no APIs exposed for async I/O on files.

Hope this helps!  If anything is unclear, let me know.

Regards,
